### ISSUE TITLE
Bild wird merkwürdig eingefügt.

### ISSUE THREAD

**Issue by andyschiffer** [julianbei/vorlage-dhbw-rv-wi#14]
# Wenn ich ein Bild hinzufüge (400x400px) ist es rechts unten umgedreht im Bild. Ich habe nur das Template genommen und es kompiliert (nichts geändert!)

https://pbs.twimg.com/profile_images/353118568/SD_cropped_400x400.jpg

![image](https://cloud.githubusercontent.com/assets/20815208/17370459/6a227584-599c-11e6-92e8-8905685b2ffe.png)

**Comment by julianbei** [comment]
Es wäre schön wenn du den Code dahinter posten könntest.
Dann könnte ich dir ggf. helfen.
Da das bild sehr groß ist, könnte es sein dass es sich um ein "korrektes" verhalten handelt.
Der rest des Screenshots lässt jedoch darauf schließen dass bei dir irgendetwas nicht korrekt compiled.
