### ISSUE TITLE
Vorlage Endet mit O’REILLY Buch

### ISSUE THREAD

**Issue by stangier** [julianbei/vorlage-dhbw-rv-wi#15]
Hallo,
warum endet die Vorlage (https://github.com/julianbei/vorlage-dhbw-rv-wi/blob/master/vorlage.pdf) mit einem O’REILLY  Buch?

**Comment by julianbei** [comment]
Weil das der Appendix ist.
Der ist hier definiert: https://github.com/julianbei/vorlage-dhbw-rv-wi/blob/master/appendix/index.tex
`pagecommand={
	\thispagestyle{fancy}
	\appsection{O'REILLY: Bootstrap}{bootstrap-book} % Appendix Titel
}`

**Comment by stangier** [comment]
Das habe ich schon verstanden, mir geht es mehr um den Zweck. Eine O'Reilly Buch über Bootstrap gehört doch nicht in ne allgemeine DHBW vorlage.

**Comment by julianbei** [comment]
natürlich nicht. Vorher war das ein Buch eines Professors. Das war jedoch nicht gewollt. daher ist dies als Trotzaktion zu werten.

Wenn es dich arg stört darfst du gerne eine Alternative vorschlagen.
